import { createPathBasedClient } from "openapi-fetch";
import { paths } from "./openapi/schema.js"; // generated by openapi-typescript
export { paths } from "./openapi/schema.js";

// export interface Options {
//     apiKey?: string,
// }

export const CalClient = createPathBasedClient<paths>;
